### PR TITLE
[fix] `rec` can be undefined in `IPS.prototype.export`

### PR DESCRIPTION
**Pull request by Destitute-Streetdwelling-Guttersnipe**
this PR fix the error in browser console:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'truncate')
    at IPS.export (ips.js:66:9)
    at self.onmessage (worker_create.js:48:31)
```

### CODE REVIEW

**Comment by marcrobledo** [comment]
Hello!
First of all, thank you for your contribution.

Can you provide an example or a patch that was failing before your fix?

**Comment by Destitute-Streetdwelling-Guttersnipe** [comment]
This error happens in creator mode when the user select the same file as original ROM and modified ROM by mistake.
If the user choose IPS, there would be an error message:
image
There's no error with other patch types.

Another case I see this error is when the modified ROM is created by truncating something from the end of the original ROM.
image
This only happens with IPS, not with other patch types.

**Comment by marcrobledo** [comment]
Thank you @Destitute-Streetdwelling-Guttersnipe, I see the error now.

But, code would be also wrong, since IPS records have no `truncate` property. That's a property for the IPS class. It was my mistake from the start :-( I figure no one reported this since the IPS creation patch where the edited ROM is smaller than the original is a very uncommon case. Definitively, the code has been incorrect since first version.

The correct code would be:
```
if(this.truncate)
```

Wanna fix it in this PR yourself? You found the bug after all and deserve credit :-)

**Comment by Destitute-Streetdwelling-Guttersnipe** [comment]
Thanks @marcrobledo for your explanation and your generosity.
I updated my patch using `this.truncate`.

**Comment by marcrobledo** [comment]
Thanks to you :-)

**Pull request merged**
